### ISSUE TITLE
Will you create asmfish for macOS? will you create matefish for macOS x64_base?

### ISSUE THREAD

**Issue by pachnes** [lantonov/asmFish#110]
Will you create asmfish for macOS? will you create matefish for macOS x64_base?

**Comment by lantonov** [comment]
Done. You can find it in https://github.com/lantonov/asmFish/tree/executables/macOS

**Comment by pachnes** [comment]
many thanks. is there a matefishX_base for macOS too?

**Comment by pachnes** [comment]
asmFishX_2018-02-12_popcount and asmFishX_2018-02-12_bmi still missing. thx for your work.

**Comment by lantonov** [comment]
Usually not but I just made one as per demand.
Compiles from Feb 11 and Feb 12 use the same code base, i. e. use 2018-02-11 for popcnt and bmi2

**Comment by MichaelB7** [comment]
Anytime anyone needs macOS , just post here and I will make it.

**Comment by pachnes** [comment]
hi, asmfish_popcnt and asmfish_bmi are missing; could you please build them?

**Comment by lantonov** [comment]
Done. Sorry, my fault to replace them with mateFish

**Comment by pachnes** [comment]
hi lantonov, thx :)

**Comment by MichaelB7** [comment]
I can do when I get home from work - about 10 hours from now.
